export const SET_USERDATA = "SET_USERDATA";
export const UPDATE_USERDATA = "UPDATE_USERDATA";
export const REMOVE_USERDATA = "REMOVE_USERDATA";

export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const UPDATE_CURRENT_PROJECT = "UPDATE_CURRENT_PROJECT";
export const REMOVE_CURRENT_PROJECT = "REMOVE_CURRENT_PROJECT";